### ISSUE TITLE
Recommended driver and kernel versions?

### ISSUE THREAD

**Issue by nioroso-x3** [949f45ac/xmr-stak-hip#3]
Hi, I was testing this miner and it only gets up to 1200 hash/s, using 16 threads 224 blocks.
Im using the ROCM packages for ubuntu 16.04  with kernel 4.15 on a vega 56. What driver version hits 1800+?

**Comment by 949f45ac** [comment]
If you are on 4.15, you must also install amdgpu-pro 18.30 with `--opencl=pal --headless` and use its dkms module. Do not use rock-dkms module.
I’ve also shortly detailed that here: https://github.com/949f45ac/xmrig-HIP#415-or-older-kernel-and-amdgpu-pro-and-rocm
To hit 1800+ you need overclock as well. If you don’t know how that works, head over here: https://github.com/RadeonOpenCompute/ROCm/issues/463 **And use soft pp table approach**, the other stuff does not really work. Soft pp tables work on kernel 4.15, no problem.

**Comment by nioroso-x3** [comment]
Ah, nice, I have other machines running with 1800+, but using the 18.10 driver to compile the kernels and 18.30 to run.
I thought rocm wouldnt run with the amdgpu-pro dkms driver.
Thanks!

**Comment by 949f45ac** [comment]
Afaik you do not need to use old compilers anymore; the `xmr-stak` devs found a way to work around the bug in the latest version.
(Now the OpenCL miner runs faster for me than this HIP miner, except on RX 570.)
